[package]
name = "pedelec-runtime"
version.workspace = true
edition.workspace = true
authors.workspace = true

[dependencies]
chrono = { workspace = true }
serde_json = { workspace = true }
uuid = { workspace = true }
pedelec-core.workspace = true
pedelec-shared.workspace = true

[dev-dependencies]
tempfile.workspace = true
