[package]
name = "pedelec-ipc"
version.workspace = true
edition.workspace = true
authors.workspace = true

[dependencies]
base64.workspace = true
dirs.workspace = true
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
pedelec-core.workspace = true
pedelec-shared.workspace = true
pedelec-runtime.workspace = true

[dev-dependencies]
pedelec-core = { workspace = true, features = ["test-support"] }
chrono.workspace = true
tempfile.workspace = true
pedelec-cli = { path = "../pedelec-cli" }
